[project]
name = "videocanvas"
version = "0.1.0"
description = "A project to convert videos to MIDI files which can be read by Roland Sound Canvas."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "mido>=1.3.3",
    "opencv-python>=4.13.0.90",
]
